Bohoo/urls.py
#! -*- coding:utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# from notification.views import *
urlpatterns = patterns(
    '',
    url(r'^$', 'Bohoo.views.main', name='main'),
    url(r'^home/$', 'Bohoo.views.index', name='index'),
    url(r'^contact/$', 'Bohoo.views.contact', name='contact_us'),     # 联系我们
    url(r'^statement/$', 'Bohoo.views.statement', name='statement'),  # 免责声明
    url(r'^about/$', 'Bohoo.views.about', name='about'),       # 关于页面
    url(r'^terms/$', 'Bohoo.views.terms', name='terms'),       # 服务条款
    url(r'^get_messages/$', 'Bohoo.views.get_messages', name='get_messages'),   # 轮询
    url(r'^captcha/', include('captcha.urls')),   # django-simple-captcha
    url(r'^search/$', 'Bohoo.views.search', name='search'),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^group_avatar/', include('group_avatar.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('social.urls')),
    url(r'^people/', include('User.urls')),
    url(r'^group/', include('groups.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
#     url(r'^admin/check_weibo_auth/$', 'blog.admin_views.check_weibo_auth'),
#     url(r'^admin/weibo/auth/$', 'blog.admin_views.admin_weibo_auth'),
#     url(r'^admin/weibo/auth/done/$', 'blog.admin_views.admin_weibo_auth_deal'),
    url(r'^group/', include('groups.urls')),
    
    url(r'^friends/', include('friends.urls')),
    url(r'^message/', include('django_messages.urls')),
    url(r'^notification/', include('sys_notification.urls'))
    
    # url(r"^settings/$", notice_settings, name="notification_notice_settings"),
)
urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

User/urls.py
#! -*- coding:utf-8 -*-

from django.conf.urls import patterns, url

urlpatterns = patterns(
    'User.views',
    url(r'^edit/$', 'edit', name='profile_edit'),
    url(r'^profile/(?P<tid>\d+)/$', 'view_profile', name='profile_view'),
    url(r'^info/(?P<tid>\d+)/$', 'view_info', name='info_view'),
    url(r'^info/add_topic/(?P<tid>\d+)/$', 'm_add_topic', name='m_add_topic'),
    url(r'^info/reply_topic/(?P<tid>\d+)/$', 'm_reply_topic', name='m_reply_topic'),
    url(r'^base_info/$', 'base_info_edit', name='base_info_edit')
)

avatar/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:
    # Django < 1.4
    from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('avatar.views',
    url(r'^add/$', 'add', name='avatar_add'),
    url(r'^change/$', 'change', name='avatar_change'),
    url(r'^delete/$', 'delete', name='avatar_delete'),
    url(r'^render_primary/(?P<user>[\w\d\.\-_]{3,30})/(?P<size>[\d]+)/$', 'render_primary', name='avatar_render_primary'),
    url(r'^list/(?P<username>[\+\w\@\.]+)/$', 'avatar_gallery', name='avatar_gallery'),
    url(r'^list/(?P<username>[\+\w\@\.]+)/(?P<id>[\d]+)/$', 'avatar', name='avatar'),
)

groups/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'groups.views',
    url(r'^new/$', 'new_group', name='new_group'),
    url(r'^edit/(?P<group_id>\d+)/$', 'edit_group', name='edit_group'),
    url(r'^add_avatar/(?P<group_id>\d+)/$', 'add_group_avatar', name='add_group_avatar'),
    url(r'^detail/(?P<group_id>\d+)/$', 'group_detail', name='group_detail'),
    url(r'^ajax_join_group/$', 'ajax_join_group', name='ajax_join_group'),
    url(r'^ajax_apply_join_group/$', 'ajax_apply_join_group', name='ajax_apply_join_group'),
    url(r'^ajax_apply_be_manager/$', 'ajax_apply_be_manager', name='ajax_apply_be_manager'),
    url(r'^ajax_quite_group/$', 'ajax_quite_group', name='ajax_quite_group'),
    url(r'^my_manager/$', 'manage', name='group_my_manage'),
    url(r'^joined/$', 'joined', name='group_joined'),
    url(r'^apply_deal/(?P<group_id>\d+)/$', 'apply_deal', name='apply_deal'),
    url(r'^ajax_apply_pass/$', 'ajax_apply_pass', name='ajax_apply_pass'),
    url(r'^ajax_apply_reject/$', 'ajax_apply_reject', name='ajax_apply_reject'),
    url(r'^add_topic/(?P<group_id>\d+)/$', 'add_topic', name='add_topic'),
    url(r'^edit_topic/(?P<group_id>\d+)/(?P<topic_id>\d+)/$', 'edit_topic', name='edit_topic'),
    url(r'^delete_topic_image/$', 'ajax_delete_topic_image', name='ajax_delete_topic_image'),
    url(r'^topic/group/$', 'group_topic', name='group_topic'),
    url(r'^topic/created/$', 'created_topic', name='created_topic'),
    url(r'^topic/relied/$', 'replied_topic', name='replied_topic'),
    url(r'^topic/detail/(?P<topic_id>\d+)/$', 'topic_detail', name='topic_detail'),
    url(r'^topic/report/$', 'ajax_report_topic', name='ajax_report_topic'),
    url(r'^reply/report/$', 'ajax_report_reply', name='ajax_report_reply'),
)

groups/models.py
#coding=utf-8

from django.conf import settings

from django.db import models

import datetime

GROUP_TYPE_CHOICES = (('open', 'Open'), ('private', 'Private'))
MEMBER_ROLE_CHOICES = ((0, 'Member'), (1, 'Manager'), (2, 'Owner'))
MEMBER_JOIN_CHOICES = (('everyone_can_join', 'Everyone can join'), ('need_check', 'Need check'))
REPORT_TYPE_CHOICES = (('topic', u'话题'), ('reply', u'回复'))
#REASON_CHOICES = ((0, u'广告或垃圾信息'), (1, u'色情、淫秽或低俗内容'), (2, u'激进时政或意识形态话题'), (3, u'其他原因'))
STATUS_CHOICES = (('enabled', u'启用'), ('disabled', u'禁用'))


class Category(models.Model):
    """
    小组分类
    字段:
    name    分类名称
    parent  父分类
    """
    name = models.CharField(max_length=200, verbose_name=u'分类', unique=True, db_index=True)
    parent = models.ForeignKey('self', related_name="category_parent", verbose_name=u'父分类', blank=True, null=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'分类'
        verbose_name_plural = u'分类'
        db_table = 'group_category'


class Group(models.Model):
    """
    小组
    字段:
    name            名称
    description     描述
    category        分类
    creator         创建人
    member          成员
    gfriend         友情小组
    group_type      小组类型
    member_join     加入小组的方式
    create_time     创建时间
    modify_time     修改时间
    is_closed       是否关闭
    last_topic_add  上一话题创建的时间
    topic_amount    话题总数
    place   群组地点
    flag    区别某些特别群组的标志,初始化时会被赋值
    manager         管理者
    """
    name = models.CharField(max_length=255, verbose_name=u'名称', unique=True, db_index=True)
    description = models.TextField(blank=True, null=True, verbose_name=u'描述')
    category = models.ForeignKey(Category, related_name='category_group', verbose_name=u'小组分类')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='creator_group', verbose_name=u'创建人')
    member = models.ManyToManyField(settings.AUTH_USER_MODEL, null=True, blank=True)
    gfriend = models.ManyToManyField('self', symmetrical=False, verbose_name=u'友情小组', null=True, blank=True)
    group_type = models.CharField(default='open', max_length=256, choices=GROUP_TYPE_CHOICES, verbose_name=u'类型')
    member_join = models.CharField(default='everyone_can_join', max_length=256, choices=MEMBER_JOIN_CHOICES,
                                   verbose_name=u'加入方式')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name=u'创建时间')
    modify_time = models.DateTimeField(default=datetime.datetime.now, verbose_name=u'修改时间')
    is_closed = models.BooleanField(default=False, verbose_name=u'是否关闭')
    last_topic_add = models.DateTimeField(null=True, blank=True, verbose_name=u'上一个话题创建的时间')
    topic_amount = models.IntegerField(default=0, verbose_name=u'话题总量')
    manager = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_manager", verbose_name=u"管理员")

    #add by lazytiger
    place = models.CharField(max_length=30, verbose_name=u'地点')
    flag = models.IntegerField(default=0, verbose_name=u'群组级别')
    #end add 

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'小组'
        verbose_name_plural = u'小组'
        db_table = 'group'

    def get_group_name(self):
        return self.name

    def get_applicant_member_num(self):
        # 返回申请加入群组的人数
        return len(self.apply_group.filter(status="processing", join_type="member"))

    def get_applicant_manager_num(self):
        # 返回申请成为群组管理员的人数
        return len(self.apply_group.filter(status="processing", join_type="manager"))

    def get_members(self):
        # 返回成员数量
        return len(self.member.all())

    def get_last_reply_order_topic_qs(self, amount=5):
        """
        返回数量为amount,默认为5,以最后回复排序的话题,返回queryset
        """
        return self.group_topic.filter(status='enabled').order_by("-last_reply_add")[:amount]


class TopicImage(models.Model):
    """
    话题图片
    image 图片
    """
    image = models.ImageField(upload_to=settings.TOPIC_IMAGE_PATH)

    def __unicode__(self):
        return "Topic Image"

    class Meta:
        verbose_name = u'话题图片'
        verbose_name_plural = u'话题图片'
        db_table = 'image_topic'

    def get_topic_image_url(self):
        path = self.image.path
        url = '/' + '/'.join(path.split('/')[3:])
        return url

    def get_topic_image_name(self):
        name = self.image.name.split('/')[-1]
        return name


class Topic(models.Model):
    """
    话题表
    字段:
    name            名称
    content         内容
    group           所在小组
    creator         创建人
    create_time     创建时间
    modify_time     修改时间
    is_closed       是否已经关闭
    is_top          是否置顶
    ilike           喜欢
    dislike         不喜欢
    last_reply_add  最新回复时间
    reply_amount    回复总数
    image           图片
    click_amount    点击次数
    status          状态
    source          来源
    
    #add by lazytiger
    topic_type      话题类型 : 1类是系统自动发布的，没有作者 ，另一类是用户发表的，需要有作者
    """
    name = models.CharField(max_length=1024, verbose_name=u'名称')
    content = models.TextField(verbose_name=u'内容')
    group = models.ForeignKey(Group, related_name='group_topic', verbose_name=u'小组')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='creator_topic', verbose_name=u'创建者')
    create_time = models.DateTimeField(default=datetime.datetime.now, verbose_name=u'创建时间')
    modify_time = models.DateTimeField(default=datetime.datetime.now, verbose_name=u'修改时间')
    is_closed = models.BooleanField(default=False, verbose_name=u'话题是否被关闭')
    is_top = models.BooleanField(default=False, verbose_name=u'是否置顶')
    ilike = models.IntegerField(default=0, verbose_name=u'顶')
    dislike = models.IntegerField(default=0, verbose_name=u'踩')
    last_reply_add = models.DateTimeField(default=datetime.datetime.now, verbose_name=u'最新回复时间')
    reply_amount = models.IntegerField(default=0, verbose_name=u'回复总数')
    image = models.ManyToManyField(TopicImage, null=True, blank=True)
    click_amount = models.FloatField(default=1, verbose_name=u'点击数')
    status = models.CharField(verbose_name=u'状态', default='enabled', max_length=56, choices=STATUS_CHOICES)
    source = models.URLField(verbose_name=u'来源', blank=True, null=True)

    topic_type = models.IntegerField(default=0, verbose_name=u'话题类型')

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'话题'
        verbose_name_plural = u'话题'
        db_table = 'topic'

    def save(self, *args, **kwargs):
        self.group.last_topic_add = datetime.datetime.now()  # 更新“最新话题添加时间”
        self.group.topic_amount += 1  # 小组话题数+1
        self.group.save()
        super(Topic, self).save(*args, **kwargs)


class Reply(models.Model):
    """
    回复表
    字段:
    content     回复内容
    creator     创建者
    topic       话题
    reply       回复
    create_time 创建时间
    status      状态
    """
    content = models.TextField(verbose_name=u'内容')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='creator_reply', verbose_name=u'创建者')
    topic = models.ForeignKey(Topic, related_name='topic_replies', verbose_name=u'话题')
    create_time = models.DateTimeField(default=datetime.datetime.now, verbose_name=u'创建时间')
    reply = models.ForeignKey('self', related_name='reply_reply', null=True, blank=True)
    status = models.CharField(verbose_name=u'状态', default='enabled', max_length=56, choices=STATUS_CHOICES)

    def __unicode__(self):
        return "%s's reply" % self.topic.name

    class Meta:
        verbose_name = u'回应'
        verbose_name_plural = u'回应'
        db_table = 'reply'

    def save(self, *args, **kwargs):
        self.topic.last_reply_add = datetime.datetime.now()  # 更新"话题的最新回复时间"
        self.topic.reply_amount += 1        # 话题回复数量+1
        self.topic.save()
        super(Reply, self).save(*args, **kwargs)


class Report(models.Model):
    """
    举报表
    字段:
    report_type   举报类型
    topic         话题
    reply         回复
    user          用户
    reason        原因
    is_handle     处理情况
    """
    report_type = models.CharField(max_length=128, choices=REPORT_TYPE_CHOICES, verbose_name=u'举报类型')
    topic = models.ForeignKey(Topic, related_name='topic_report', null=True, blank=True)
    reply = models.ForeignKey(Reply, related_name='reply_report', null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_report')
    reason = models.TextField(verbose_name=u'举报原因')
    is_handle = models.BooleanField(default=False, verbose_name=u'处理情况')

    def __unicode__(self):
        return self.topic

    class Meta:
        verbose_name = u'举报'
        verbose_name_plural = u'举报'
        db_table = 'report'



APPLY_STATUS = (('processing', u'处理中'), ('pass', u'通过'), ('rejected', u'未通过'))


class Applicant(models.Model):
    """
    `用户申请加入群组表(group_type为private的群组加入需要通过申请)`
    applicant    申请人
    group        申请加入的小组
    reason       申请理由
    status       状态(处理中,通过,未通过)(processing,pass,rejected)
    join_type         类型(加入群组,群组管理员)(member,manager)
    """
    applicant = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='applicant_user', verbose_name=u'申请人')
    group = models.ForeignKey(Group, related_name='apply_group', verbose_name=u'申请加入的小组')
    reason = models.TextField(verbose_name=u'理由', blank=True, null=True)
    apply_time = models.DateTimeField(verbose_name=u'申请时间', auto_now_add=True)
    status = models.CharField(max_length=256, default='processing', verbose_name=u'状态')
    join_type = models.CharField(max_length=128, verbose_name=u'类型')

    def __unicode__(self):
        return self.applicant

    class Meta:
        verbose_name = u'申请加入群组/成为管理员'
        verbose_name_plural = u'申请加入群组/成为管理员'
        db_table = 'applicant'

groups/templates/groups/new/add_avatar.html
{% extends "group_base.html" %}
{% load group_avatar_tags %}

{% block head_other %}
    <style type="text/css">
    .group_avatar img{
        padding-bottom: 14px;
    }
    </style>
{% endblock %}

{% block title %}
    {{ group.name }}-添加头像
{% endblock %}

{% block right_content %}
    <h3><span class="text-info">{{ group.name }}</span>--<span class="muted">添加群组头像</span></h3>
    <div class="row-fluid profile-box">
        <div class="profile-box-module">
            <div class="span3">
                <span class="text-info">头像</span>
            </div>
            <div class="span3 group_avatar">
                {% group_avatar group %}
            </div>
            <div class="span6">
                <span><a href="{% url 'group_avatar_change' group_id=group.id %}">修改头像</a></span>
                <span><a href="{% url 'group_avatar_delete' group_id=group.id%}">删除头像</a></span>
            </div>
        </div>
    </div>
{% endblock %}

groups/templates/groups/new/group.html
{% extends "group_base.html" %}
{% load group_avatar_tags %}

{% block title %}创建群组{% endblock %}
{% block head_other %}
    <style type="text/css">
        .box {
            margin: 0 0 25px;
            clear: both;
            border-radius: 4px;
            border: 2px solid #ddd;
            box-shadow: 0 1px 0 #f2f4f5;
        }

        .box-module {
            position: relative;
            padding: 20px 12px;
        }

        .box-module+.box-module {
            border-top: 1px solid #ddd;;
        }

        .empty-error {
            background-color: #da4f49;
        }
        #id_description{
            height: 100px;
        }
    </style>
{% endblock %}

{% block left_content %}
{% endblock %}


{% block right_content %}
    <form method="post" id="new-group-form">
        <div class="row-fluid box">
            <div class="box-module">
                <div class="row-fluid">
                    <div class="span3">
                        <span class="text-info"><span class="mustin">*</span>{{ form.group_type.label }}</span>
                    </div>
                    <div class="span9">
                        {{ form.group_type }}
{#                    <span class="help-inline">#}
{#                        <span class="text-warning">公开:任何人可见;秘密:需群组成员发出邀请才可加入.</span>#}
{#                    </span>#}
                    </div>
                </div>
            </div>

            <div class="box-module">
                <div class="row-fluid">
                    <div class="span3">
                        <span class="text-info"><span class="mustin">*</span>{{ form.member_join.label }}</span>
                    </div>
                    <div class="span9">
                        {{ form.member_join }}
                    <span class="help-inline">
                        <span class="text-warning">任何人:任何用户都可以加入,无需验证<br/>需要验证:需群组管理员同意后才能加入群组</span>
                    </span>
                    </div>
                </div>
            </div>

            <div class="box-module">
                <div class="row-fluid">
                    <div class="span3">
                        <span class="text-info"><span class="mustin">*</span>{{ form.name.label }}</span>
                    </div>
                    <div class="span9">
                        {{ form.name }}
                    </div>
                </div>
            </div>

            <div class="box-module">
                <div class="row-fluid">
                    <div class="span3">
                        <span class="text-info"><span class="mustin">*</span>分类</span>
                    </div>
                    <div class="span4">
                            <select class="span10" id="job_category">
                                <option class="">---</option>
                                <option value="it" class="it">计算机软件/互联网</option>
                                <option value="elec" class="elec">通信/电子</option>
                                <option value="trade" class="trade">贸易/批发/零售</option>
                                <option value="finance" class="finance">会计/金融</option>
                                <option value="medical" class="medical">制药/生物/医疗</option>
                                <option value="culture" class="culture">文化/广告/媒体</option>
                                <option value="building" class="building">房地产/建筑</option>
                                <option value="education" class="education">教育/培训/科研</option>
                                <option value="professional" class="professional">专业服务</option>
                                <option value="machine" class="machine">加工/机械/制造</option>
                                <option value="traffic" class="traffic">物流/运输</option>
                                <option value="services" class="services">服务行业</option>
                                <option value="energy" class="energy">能源/化工/原材料</option>
                                <option value="government" class="government">政府/其他</option>
                            </select>
                        </div>
                    <div class="span4">
                        <select class="span11 required" id="id_category" name="category" disabled="disabled">
                            <option value="" selected="selected">---</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="box-module">
                <div class="row-fluid">
                    <div class="span3">
                        <span class="text-info"><span class="mustin">*</span>{{ form.place.label }}</span>
                    </div>
                    <div class="span9">
                        {{ form.place }}
                    </div>
                </div>
            </div>

            <div class="box-module">
                <div class="row-fluid">
                    <div class="span3">
                        <span class="text-info"><span class="mustin">*</span>{{ form.description.label }}</span>
                    </div>
                    <div class="span9">
                        {{ form.description }}
                    </div>
                </div>
            </div>

            <div class="box-module">
                <div class="row-fluid">
                    <div class="span6">
                        {% csrf_token %}<input type="submit" class="btn btn-primary btn-block" id="id-submit">
                    </div>
                    <div class="span6">
                        <input type="reset" class="btn btn-info btn-block">
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

{% block js_other %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.chained.min.js"></script>
    <script type="text/javascript" src={{ STATIC_URL }}js/job_category.js></script>  {# 引进job_category数据 #}
    <script type="text/javascript">
        // 分类的联动处理
        var job_category = eval(job_categories.job_category);
        for (var k = 0;k < job_category.length; k++){
            var jobs = eval(job_category[k].jobs);
            for (var l = 0; l < jobs.length; l++){
                $("#id_category").append("<option value='"+ jobs[l].job + "' class='" + job_category[k].category + "'>" + jobs[l].job + "</option>")
            }
        }
        $("#id_category").chained("#job_category");

        $("#id-submit").on('click', function (e) {
            e.preventDefault();
            var pass_check = true;
            $('.required').each(function () {
                if (!$(this).val()) {
                    $(this).parents('.box-module').addClass("empty-error");
                    $.globalMessenger().post({
                        message: "以*号标注的项不能为空!",
                        hideAfter: 2,
                        type: 'error',
                        showCloseButton: true
                    });
                    pass_check = false;
                    return false;
                }
            });
            if (pass_check) {
                $("#new-group-form").submit();
            }
        })
    </script>
{% endblock %}