Bohoo/urls.py
#! -*- coding:utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# from notification.views import *
urlpatterns = patterns(
    '',
    url(r'^$', 'Bohoo.views.main', name='main'),
    url(r'^home/$', 'Bohoo.views.index', name='index'),
    url(r'^contact/$', 'Bohoo.views.contact', name='contact_us'),     # 联系我们
    url(r'^statement/$', 'Bohoo.views.statement', name='statement'),  # 免责声明
    url(r'^about/$', 'Bohoo.views.about', name='about'),       # 关于页面
    url(r'^terms/$', 'Bohoo.views.terms', name='terms'),       # 服务条款
    url(r'^get_messages/$', 'Bohoo.views.get_messages', name='get_messages'),   # 轮询
    url(r'^captcha/', include('captcha.urls')),   # django-simple-captcha
    url(r'^search/$', 'Bohoo.views.search', name='search'),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^group_avatar/', include('group_avatar.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('social.urls')),
    url(r'^people/', include('User.urls')),
    url(r'^group/', include('groups.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
#     url(r'^admin/check_weibo_auth/$', 'blog.admin_views.check_weibo_auth'),
#     url(r'^admin/weibo/auth/$', 'blog.admin_views.admin_weibo_auth'),
#     url(r'^admin/weibo/auth/done/$', 'blog.admin_views.admin_weibo_auth_deal'),
    url(r'^group/', include('groups.urls')),
    
    url(r'^friends/', include('friends.urls')),
    url(r'^message/', include('django_messages.urls')),
    url(r'^notification/', include('sys_notification.urls'))
    
    # url(r"^settings/$", notice_settings, name="notification_notice_settings"),
)
urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

User/urls.py
#! -*- coding:utf-8 -*-

from django.conf.urls import patterns, url

urlpatterns = patterns(
    'User.views',
    url(r'^edit/$', 'edit', name='profile_edit'),
    url(r'^profile/(?P<tid>\d+)/$', 'view_profile', name='profile_view'),
    url(r'^info/(?P<tid>\d+)/$', 'view_info', name='info_view'),
    url(r'^info/add_topic/(?P<tid>\d+)/$', 'm_add_topic', name='m_add_topic'),
    url(r'^info/reply_topic/(?P<tid>\d+)/$', 'm_reply_topic', name='m_reply_topic'),
    url(r'^base_info/$', 'base_info_edit', name='base_info_edit')
)

avatar/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:
    # Django < 1.4
    from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('avatar.views',
    url(r'^add/$', 'add', name='avatar_add'),
    url(r'^change/$', 'change', name='avatar_change'),
    url(r'^delete/$', 'delete', name='avatar_delete'),
    url(r'^render_primary/(?P<user>[\w\d\.\-_]{3,30})/(?P<size>[\d]+)/$', 'render_primary', name='avatar_render_primary'),
    url(r'^list/(?P<username>[\+\w\@\.]+)/$', 'avatar_gallery', name='avatar_gallery'),
    url(r'^list/(?P<username>[\+\w\@\.]+)/(?P<id>[\d]+)/$', 'avatar', name='avatar'),
)

group_avatar/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:
    # Django < 1.4
    from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('group_avatar.views',
                       url(r'^group_add/(?P<group_id>\d+)/$', 'group_add', name='group_avatar_add'),
                       url(r'^group_change/(?P<group_id>\d+)/$', 'group_change', name='group_avatar_change'),
                       url(r'^group_delete/(?P<group_id>\d+)/$', 'group_delete', name='group_avatar_delete'),
                       url(r'^group_render_primary/(?P<group>[\w\d\.\-_]{3,30})/(?P<size>[\d]+)/$',
                           'group_render_primary', name='group_avatar_render_primary'),
                       url(r'^group_list/(?P<group_name>[\+\w\@\.]+)/$', 'group_avatar_gallery',
                           name='group_avatar_gallery'),
                       url(r'^group_list/(?P<group_name>[\+\w\@\.]+)/(?P<id>[\d]+)/$', 'group_avatar',
                           name='group_avatar'),
                       )

User/models.py
#coding=utf-8
import datetime
import utils

from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.contrib.auth.signals import user_logged_in


class MyUserManager(BaseUserManager):
    # 创建用户
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        if not username:
            raise ValueError('Users must have a username')
        if not password:
            raise ValueError('Users must have a password')

        user = self.model(
            email=MyUserManager.normalize_email(email),
            username=username,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    # 创建超级用户
    def create_superuser(self, email, username, password):
        user = self.create_user(email=email,
                                username=username,
                                password=password
                                )
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser, PermissionsMixin):
    """
    ``用户表``
    email 邮件
    username 用户名
    sign  签名
    job 工作
    activation_key  激活码
    date_joined  注册时间
    avatar  头像
    first_name 名
    last_name 姓
    is_active 允许登录
    is_admin  管理员
    follower  关注者
    sex   性别
    birthday  生日
    country   国家
    state     州省
    city    区县
    qq      qq号码
    weibo   微博帐号
    phone_number  电话号码
    lastest_login  最近登录时间
    """
    SEX_CHOICES = (('M', u'男'), ('F', u'女'))
    email = models.EmailField(max_length=255, verbose_name=u'邮箱', unique=True, db_index=True)
    username = models.CharField(max_length=100, verbose_name=u'用户名', unique=True, db_index=True)
    sign = models.CharField(max_length=1024, verbose_name=u'签名', null=True, blank=True)
    job = models.CharField(max_length=1024, verbose_name=u'职业', null=True, blank=True, default=None)
    activation_key = models.CharField(max_length=40, verbose_name=u'激活码', blank=True)
    date_joined = models.DateTimeField(auto_now_add=True, verbose_name=u'注册时间')
    # avatar = models.ImageField(upload_to='user_avatar/%Y/%m/%d', blank=True, null=True, verbose_name=u'头像')
    first_name = models.CharField(max_length=256, verbose_name=u'名', null=True, blank=True)
    last_name = models.CharField(max_length=256, verbose_name=u'姓', null=True, blank=True)
    is_active = models.BooleanField(default=True, verbose_name=u'是否允许用户登录')
    is_admin = models.BooleanField(default=False, verbose_name=u'是否管理员')
    follower = models.ManyToManyField('self')
    sex = models.CharField(max_length=128, verbose_name=u'性别', null=True, blank=True, choices=SEX_CHOICES)
    birthday = models.DateField(verbose_name=u'生日', null=True, blank=True)
    country = models.CharField(max_length=256, verbose_name=u'国家', null=True, blank=True)
    state = models.CharField(max_length=256, verbose_name=u'州省', null=True, blank=True)
    city = models.CharField(max_length=256, verbose_name=u'区县', null=True, blank=True)
    qq = models.IntegerField(verbose_name=u'qq', null=True, blank=True)
    weibo = models.CharField(max_length=256, verbose_name=u'微博', null=True, blank=True)
    phone_number = models.CharField(max_length=25, verbose_name=u'手机', null=True, blank=True)
    latest_login = models.DateTimeField(verbose_name=u'最近登录', null=True, blank=True)
    objects = MyUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def get_full_name(self):
        # 返回全名
        return self.last_name + self.first_name

    def get_short_name(self):
        # 返回名字
        return self.first_name

    def get_username(self):
        # 返回用户名
        return self.username

    def __unicode__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        """Does the user have a specific permission?"""
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        """Does the user have permissions to view the app `app_label`?"""
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        """Is the user a member of staff?"""
        # Simplest possible answer: All admins are staff
        return self.is_admin

User/views.py
# coding=utf-8
# -*- coding:utf-8 -*-
import json
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import loader, RequestContext
from django.shortcuts import redirect, get_object_or_404
from django.utils.datastructures import MultiValueDictKeyError
from Bohoo.settings import JOINED_GROUPS_NUM, ADD_TOPIC_NUM, REPLY_TOPIC_NUM

from User.models import MyUser
from User.forms import UserInfo
from friends.models import Friendship
from groups.models import Topic, Reply

from groups.utils import get_groups


@login_required()
def edit(request):
    """
    编辑个人资料
    @fanlintao
    """
    if request.method == "POST":
        form = UserInfo(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
    vt = loader.get_template("people/edit.html")
    c = RequestContext(
        request, {
            'form': UserInfo(instance=request.user)
        }
    )
    return HttpResponse(vt.render(c))


def view_profile(request, tid):
    """
    查看个人资料
    @fanlintao
    """
    t_user = get_object_or_404(MyUser, id=tid)
    #关注了
    t_followed = Friendship.objects.filter(from_user=t_user)

    # 关注者
    t_follower = Friendship.objects.filter(to_user=t_user)

    vt = loader.get_template("people/profile.html")
    c = RequestContext(
        request, {
            'user': t_user,
            'followed': t_followed,
            'follower': t_follower
        }
    )
    return HttpResponse(vt.render(c))


def view_info(request, tid):
    """
    查看他人资料: 加入的群组
    @fanlintao
    """
    t_user = get_object_or_404(MyUser, id=tid)
    t_joined_groups = get_groups(t_user)[0:JOINED_GROUPS_NUM:-1]   # 加入的群组
    active_tab = 'followed'    # 默认激活'关注了'的tab


    #关注了
    t_followed = Friendship.objects.filter(from_user=t_user)

    # 关注者
    t_follower = Friendship.objects.filter(to_user=t_user)

    try:
        if request.method == 'GET':
            f_user = get_object_or_404(MyUser, id=request.GET['follow_user'])
            t_followed = Friendship.objects.filter(from_user=f_user)
            t_follower = Friendship.objects.filter(to_user=f_user)
            active_tab = request.GET['follow_type']
    except MultiValueDictKeyError:
        pass

    # 是否已经关注
    is_followed = False
    if not request.user.is_anonymous():
        f_list = Friendship.objects.filter(from_user=request.user, to_user=t_user).values_list('from_user', flat=True)
    else:
        f_list = []
    if request.user.id in f_list:
        is_followed = True

    vt = loader.get_template("people/member_info/group_joined.html")
    c = RequestContext(
        request, {
            't_user': t_user,
            'is_followed': is_followed,
            'joined_groups': t_joined_groups,
            'followed': t_followed,
            'follower': t_follower,
            'active_tab': active_tab
        }
    )
    return HttpResponse(vt.render(c))


def m_add_topic(request, tid):
    """
    查看他人资料: 添加的话题
    @fanlintao
    """
    t_user = get_object_or_404(MyUser, id=tid)
    t_add_topic = Topic.objects.filter(creator=t_user).order_by('-create_time')[0:ADD_TOPIC_NUM]   # 添加的话题

    active_tab = 'followed'    # 默认激活'关注了'的tab


    #关注了
    t_followed = Friendship.objects.filter(from_user=t_user)

    # 关注者
    t_follower = Friendship.objects.filter(to_user=t_user)

    try:
        if request.method == 'GET':
            f_user = get_object_or_404(MyUser, id=request.GET['follow_user'])
            t_followed = Friendship.objects.filter(from_user=f_user)
            t_follower = Friendship.objects.filter(to_user=f_user)
            active_tab = request.GET['follow_type']
    except MultiValueDictKeyError:
        pass

    # 是否已经关注
    is_followed = False
    if not request.user.is_anonymous():
        f_list = Friendship.objects.filter(from_user=request.user, to_user=t_user).values_list('from_user', flat=True)
    else:
        f_list = []
    if request.user.id in f_list:
        is_followed = True

    vt = loader.get_template("people/member_info/topic_add.html")
    c = RequestContext(
        request, {
            't_user': t_user,
            'is_followed': is_followed,
            'add_topics': t_add_topic,
            'followed': t_followed,
            'follower': t_follower,
            'active_tab': active_tab
        }
    )
    return HttpResponse(vt.render(c))


def m_reply_topic(request, tid):
    """
    查看他人资料: 回复的话题
    @fanlintao
    """
    t_user = get_object_or_404(MyUser, id=tid)
    t_r_topic_ids = Reply.objects.filter(creator=t_user, reply__isnull=True,
                                         topic__isnull=False).values_list('topic', flat=True)
    t_reply_topics = Topic.objects.filter(id__in=list(set(t_r_topic_ids))).order_by('-create_time')[0:REPLY_TOPIC_NUM]
    active_tab = 'followed'    # 默认激活'关注了'的tab


    #关注了
    t_followed = Friendship.objects.filter(from_user=t_user)

    # 关注者
    t_follower = Friendship.objects.filter(to_user=t_user)

    try:
        if request.method == 'GET':
            f_user = get_object_or_404(MyUser, id=request.GET['follow_user'])
            t_followed = Friendship.objects.filter(from_user=f_user)
            t_follower = Friendship.objects.filter(to_user=f_user)
            active_tab = request.GET['follow_type']
    except MultiValueDictKeyError:
        pass

    # 是否已经关注
    is_followed = False
    if not request.user.is_anonymous():
        f_list = Friendship.objects.filter(from_user=request.user, to_user=t_user).values_list('from_user', flat=True)
    else:
        f_list = []
    if request.user.id in f_list:
        is_followed = True

    vt = loader.get_template("people/member_info/topic_reply.html")
    c = RequestContext(
        request, {
            't_user': t_user,
            'is_followed': is_followed,
            'reply_topics': t_reply_topics,
            'followed': t_followed,
            'follower': t_follower,
            'active_tab': active_tab
        }
    )
    return HttpResponse(vt.render(c))


@login_required()
def base_info_edit(request):
    """
    编辑基本资料
    @fanlintao
    """

    if request.method == "POST":
        form = UserInfo(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect(reverse('index'))
    vt = loader.get_template("people/base_info_edit.html")
    c = RequestContext(
        request, {
            'form': UserInfo(instance=request.user)
        }
    )
    return HttpResponse(vt.render(c))

User/templates/people/edit.html
{% extends 'people_base.html' %}
{% load avatar_tags %}

{% block title %}编辑个人资料-BOHOO{% endblock %}

{% block description %}编辑用户资料{% endblock %}

{% block head_other %}
    <style type="text/css">
    .profile-box{
        margin: 0 0 25px;
        clear: both;
        border-radius: 4px;
        border: 2px solid #ddd;
        box-shadow: 0 1px 0 #f2f4f5;
    }
    .profile-box-module{
        position: relative;
        padding: 20px 12px;
    }
    .profile-box-module+.profile-box-module{
        border-top: 1px solid #ddd;;
    }
    .avatar img{
        padding-bottom: 14px;
    }
    .sex ul{
        list-style-type: none;
    }
    .sex ul li{
        display: inline-block;
        margin-left: 5px;
        margin-right: 10px;
    }
    </style>
{% endblock %}

{% block js_other %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.chained.min.js"></script>
    <script type="text/javascript" src={{ STATIC_URL }}js/cities.js></script>  {# 引进cities数据 #}
    <script type="text/javascript" src={{ STATIC_URL }}js/job_category.js></script>  {# 引进job_category数据 #}
    <script type="text/javascript">
    // 国家-州省-市县 的三级联动
    $(document).ready(function(){
        $("#id_country").append(
                "<option value='中国' class='china'>中国</option>"+
                "<option value='其他' class='china'>其他</option>"
        );
        var provinces = eval(cities.provinces);
        for (var i = 0; i < provinces.length; i++){
            if (provinces[i].name != "海外"){
                $('#id_state').append("<option value='"+ provinces[i].name + "' class='中国'>" + provinces[i].name + "</option>");
            }else{
                $('#id_state').append("<option value='"+ provinces[i].name + "' class='其他'>" + provinces[i].name + "</option>");

            }
            $('#id_state').append("<option value='"+ provinces[i].name + "' class='" + provinces[i].name + "'>" + provinces[i].name + "</option>");
            var city = eval(provinces[i].citys);
            for (var j = 0; j < city.length; j ++){
                $("#id_city").append("<option value='"+ city[j].city + "' class='" + provinces[i].name + "'>" + city[j].city + "</option>");
            }
        }
        $("#id_state").chained("#id_country");
        $("#id_city").chained("#id_state");

        // 职业的联动处理
        var job_category = eval(job_categories.job_category);
        for (var k = 0;k < job_category.length; k++){
            var jobs = eval(job_category[k].jobs);
            for (var l = 0; l < jobs.length; l++){
                $("#id_job").append("<option value='"+ jobs[l].job + "' class='" + job_category[k].category + "'>" + jobs[l].job + "</option>")
            }
        }
        $("#id_job").chained("#job_category");

        // 给初始值
        var $job = "{{ request.user.job }}";
        if ($job != 'None'){
            $("#id_job").append("<option value='" + $job + "' class='" + $job + "' selected='selected'>" + $job +"</option>");
        }
        var $country = "{{ request.user.country }}";
        if($country != 'None'){
            $("#id_country").append("<option value='" + $country + "' class='" + $country + "' selected='selected'>" + $country +"</option>");
        }
        var $state = "{{ request.user.state }}";
        if($state != 'None'){
            $("#id_state").append("<option value='" + $state + "' class='" + $state + "' selected='selected'>" + $state +"</option>");
        }
        var $city = "{{ request.user.city }}";
        if($city != 'None'){
            $("#id_city").append("<option value='" + $city + "' class='" + $city + "' selected='selected'>" + $city +"</option>");
        }
    })
    </script>
{% endblock %}

{% block left_content %}
    <div class="row-fluid profile-box">
        <div class="profile-box-module">
            <div class="span6">
                <span class="pull-left"><a href="#">{{ request.user.username }}</a>
                    <i class="icon-double-angle-right"></i>编辑个人资料</span>
            </div>
            <div class="span3">
                <span class="pull-right"><a href="{% url 'reset_password' user_id=request.user.id %}">修改密码</a></span>
            </div>
            <div class="span3">
                <span class="pull-right"><a href="{% url 'profile_view' tid=request.user.id %}">返回个人主页</a></span>
            </div>
        </div>
    </div>

    <div class="row-fluid profile-box">
        <div class="profile-box-module">
            <div class="span3">
                <span class="text-info">头像</span>
            </div>
            <div class="span3 avatar">
                {% avatar request.user %}
            </div>
            <div class="span3">
                <span class="pull-right"><a href="{% url 'avatar_change' %}">修改头像</a></span>
            </div>
            <div class="span3">
                <span class="pull-right"><a href="{% url 'avatar_delete' %}">删除头像</a></span>
            </div>
        </div>
    </div>

<form method="post">
    <div class="profile-box">
        <div class="profile-box-module">
            <div class="row-fluid">
                <div class="span12">
                    <div class="row-fluid">
                        <div class="span2">
                            <span class="text-info">{{ form.sign.label }}</span>
                        </div>
                        <div class="span10">
                            {{ form.sign }}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="profile-box-module">
            <div class="row-fluid">
                <div class="span6">
                    <div class="row-fluid">
                        <div class="span4">
                            <span class="text-info">{{ form.last_name.label }}</span>
                        </div>
                        <div class="span8">
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="span6">
                    <div class="row-fluid">
                        <div class="span4">
                            <span class="text-info">{{ form.first_name.label }}</span>
                        </div>
                        <div class="span8">
                            {{ form.first_name }}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="profile-box-module">
            <div class="row-fluid">
                <div class="span6">
                    <div class="row-fluid">
                        <div class="span4">
                            <span class="text-info">{{ form.sex.label }}</span>
                        </div>
                        <div class="span8 sex">
                            {{ form.sex }}
                        </div>
                    </div>
                </div>
                <div class="span6">
                    <div class="row-fluid">
                        <div class="span4">
                            <span class="text-info">{{ form.phone_number.label }}</span>
                        </div>
                        <div class="span8">
                            {{ form.phone_number }}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="profile-box-module">
            <div class="row-fluid">
                <div class="span6">
                    <div class="row-fluid">
                        <div class="span4">
                            <span class="text-info">{{ form.birthday.label }}</span>
                        </div>
                        <div class="span8">
                            {{ form.birthday }}
                        </div>
                    </div>
                </div>
                <div class="span6">
                    <div class="row-fluid">
                        <div class="span4">
                            <span class="text-info">{{ form.job.label }}</span>
                        </div>
                        <div class="span8">
                            <select class="span10" id="job_category">
                                <option class="">---</option>
                                <option value="it" class="it">计算机软件/互联网</option>
                                <option value="elec" class="elec">通信/电子</option>
                                <option value="trade" class="trade">贸易/批发/零售</option>
                                <option value="finance" class="finance">会计/金融</option>
                                <option value="medical" class="medical">制药/生物/医疗</option>
                                <option value="culture" class="culture">文化/广告/媒体</option>
                                <option value="building" class="building">房地产/建筑</option>
                                <option value="education" class="education">教育/培训/科研</option>
                                <option value="professional" class="professional">专业服务</option>
                                <option value="machine" class="machine">加工/机械/制造</option>
                                <option value="traffic" class="traffic">物流/运输</option>
                                <option value="services" class="services">服务行业</option>
                                <option value="energy" class="energy">能源/化工/原材料</option>
                                <option value="government" class="government">政府/其他</option>
                            </select>
                            {{ form.job }}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="profile-box-module">
            <div class="row-fluid">
                <div class="span6">
                    <div class="row-fluid">
                        <div class="span4">
                            <span class="text-info">{{ form.qq.label }}</span>
                        </div>
                        <div class="span8">
                            {{ form.qq }}
                        </div>
                    </div>
                </div>
                <div class="span6">
                    <div class="row-fluid">
                        <div class="span4">
                            <span class="text-info">{{ form.weibo.label }}</span>
                        </div>
                        <div class="span8">
                            {{ form.weibo }}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="profile-box-module">
            <div class="row-fluid">
                <div class="span4">
                    <div class="row-fluid">
                        <div class="span4">
                            <span class="text-info">{{ form.country.label }}</span>
                        </div>
                        <div class="span8">
                            {{ form.country }}
                        </div>
                    </div>
                </div>
                <div class="span4">
                    <div class="row-fluid">
                        <div class="span4">
                            <span class="text-info">{{ form.state.label }}</span>
                        </div>
                        <div class="span8">
                            {{ form.state }}
                        </div>
                    </div>
                </div>
                <div class="span4">
                    <div class="row-fluid">
                        <div class="span4">
                            <span class="text-info">{{ form.city.label }}</span>
                        </div>
                        <div class="span8">
                            {{ form.city }}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="profile-box-module">
            <div class="row-fluid">
                <div class="span12">
                    {% csrf_token %}<input class="btn btn-primary btn-block" type="submit" value="保存">
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

{% block right_content %}
<!-- TODO: 右边栏 -->
{% endblock %}